export const HANDLEMESSAGESHOW = 'HANDLEMESSAGESHOW';
export const HANDLEMESSAGEHIDE = 'HANDLEMESSAGEHIDE';
export const HANDLEMESSAGECONFIRMATION = 'HANDLEMESSAGECONFIRMATION';
export const HANDLEMESSAGECLEAR = 'HANDLEMESSAGECLEAR';