// attribute section
export const ADD_ATTRIBUTESECTION = 'ADD_ATTRIBUTESECTION';
export const DELETE_ATTRIBUTESECTION = 'DELETE_ATTRIBUTESECTION';
export const EDIT_ATTRIBUTESECTION = 'EDIT_ATTRIBUTESECTION';
export const FIND_ATTRIBUTESECTION = 'FIND_ATTRIBUTESECTION';

// attribute section Search
export const HANDLESEARCHATTRIBUTE = 'HANDLESEARCHATTRIBUTE';
export const HANDLESEARCH = 'HANDLESEARCH';
export const HANDLESEARCHSUCCESS = 'HANDLESEARCHSUCCESS';
export const HANDLESEARCHFAIL = 'HANDLESEARCHFAIL';
export const HANDLESEARCHCHANGES = 'HANDLESEARCHCHANGES';
export const HANDLEREMOVEDATA = 'HANDLEREMOVEDATA';
export const RESETSEARCH = 'RESETSEARCH';
export const STOREPREVIEW = 'STOREPREVIEW';
export const AUTOUPDATE = 'AUTOUPDATE';
export const GETSYNONYMSLIST = 'GETSYNONYMSLIST';
export const GETSYNONYMSLISTSUCCESS = 'GETSYNONYMSLISTSUCCESS';
export const GETSYNONYMSLISTERROR = 'GETSYNONYMSLISTERROR';
export const UPDATESYNONYMS = 'UPDATESYNONYMS';

// attribute section delete
export const HANDLEDELETE = 'HANDLEDELETE';
export const HANDLEDELETESUCCESS = 'HANDLEDELETESUCCESS';
export const HANDLEDELETEFAIL = 'HANDLEDELETEFAIL';
export const HANDLECUSTOMHEADER = 'HANDLECUSTOMHEADER';

//mapping section
export const HANDLEATTRIBUTELIST = 'HANDLEATTRIBUTELIST';
export const HANDLEATTRIBUTELISTSUCCESS = 'HANDLEATTRIBUTELISTSUCCESS';
export const HANDLEATTRIBUTELISTERROR = 'HANDLEATTRIBUTELISTERROR';
export const HANDLEATTRIBUTELISTCHANGES = 'HANDLEATTRIBUTELISTCHANGES';
export const HANDLEMAPPEDCHNAGES = 'HANDLEMAPPEDCHNAGES';
export const SAVEMAPPEDDATA = 'SAVEMAPPEDDATA';
export const SAVEMAPPEDDATASUCCESS = 'SAVEMAPPEDDATASUCCESS';
export const SAVEMAPPEDDATAERROR = 'SAVEMAPPEDDATAERROR';
export const PERSISTMAPPINGDATA = 'PERSISTMAPPINGDATA';
export const HANDLETABLEINLIST = 'HANDLETABLEINLIST';

//home Section
export const HANDLESELECTEDFILE = 'HANDLESELECTEDFILE';
export const HANDLESELECTEDDEFAULTVALUE='HANDLESELECTEDFILE';

//selectMapping
export const HANDLESELECTEDMAP = 'HANDLESELECTEDMAP';
export const LOADLIST = 'LOADLIST';
export const LOADLISTSUCCESS = 'LOADLISTSUCCESS';
export const LOADLISTFAIL = 'LOADLISTFAIL';
export const SETPREVIEW = 'SETPREVIEW';
export const SETHOME = 'SETHOME';

//edit mapping
export const GETCSVDATA = 'GETCSVDATA';
export const GETCSVDATASUCCESS = 'GETCSVDATASUCCESS';
export const GETCSVDATAFAIL = 'GETCSVDATAFAIL';
export const GETMAPINFO = 'GETMAPINFO';
export const GETMAPINFOSUCCESS = 'GETMAPINFOSUCCESS';
export const GETMAPINFOFAIL = 'GETMAPINFOFAIL';
export const UPDATEMAPPING = 'UPDATEMAPPING';
export const UPDATEMAPPINGSUCCESS = 'UPDATEMAPPINGSUCCESS';
export const UPDATEMAPPINGFAIL = 'UPDATEMAPPINGFAIL';
export const HANDLEREDIRECT = 'HANDLEREDIRECT';

//MESSAGES
export const SHOWMESSAGE = 'SHOWMESSAGE';
export const SHOWCSVERRMSG = 'SHOWCSVERRMSG';


//CSV
export const DUMMY = 'DUMMY';
export const HANDLECHANGEVIEW= 'HANDLECHANGEVIEW';
export const HANDLECSVUPLOAD = 'HANDLECSVUPLOAD';
export const HANDLECSVUPLOADSUCCESS = 'HANDLECSVUPLOADSUCCESS';
export const HANDLECSVUPLOADFAIL = 'HANDLECSVUPLOADFAIL';
export const HANDLECSVPREVIOUSVIEW = 'HANDLECSVPREVIOUSVIEW';
export const HANDLECSVNEXTVIEW = 'HANDLECSVNEXTVIEW';

//CSV Preview
export const HANDLECSVPREVIEWHEADERCHANGE = 'HANDLECSVPREVIEWHEADERCHANGE';
export const HANDLECSVPREVIEWDELIMITER = 'HANDLECSVPREVIEWDELIMITER';
export const HANDLECSVPREVIEWDATE = 'HANDLECSVPREVIEWDATE';
export const HANDLECSVPREVIEWNUMBER = 'HANDLECSVPREVIEWNUMBER';
export const HANDLEPREVIEWSETTING = 'HANDLEPREVIEWSETTING';
export const HANDLECSVLOADTABLES = 'HANDLECSVLOADTABLES';
export const HANDLECSVMAPCOLUMNCHANGE = 'HANDLECSVMAPCOLUMNCHANGE';
export const HANDLECSVMAPTABLECHANGE = 'HANDLECSVMAPTABLECHANGE';
export const HANDLECSVMAPTABLEINDEXCHANGE = 'HANDLECSVMAPTABLEINDEXCHANGE';
export const HANDLECSVMAPREMOVE = 'HANDLECSVMAPREMOVE';
export const HANDLECSVMAPPROPERTYCHANGE = 'HANDLECSVMAPPROPERTYCHANGE';
export const HANDLECSVMAPADD = 'HANDLECSVMAPADD';
export const HANDLECSVMAPPING = 'HANDLECSVMAPPING';
export const HANDLEATTRIBUTEMAPPING = 'HANDLEATTRIBUTEMAPPING';
export const HANDLEDEFAULTVALUECHANGE = 'HANDLEDEFAULTVALUECHANGE';
export const HANDLECSVMAPDATAREMOVE = 'HANDLECSVMAPDATAREMOVE';
export const HANDLEAUTOMAPPING = 'HANDLEAUTOMAPPING';
export const HANDLEMAPPINGNAME = 'HANDLEMAPPINGNAME';
export const HANDLECSVMAPTRANSFORMATION = 'HANDLECSVMAPTRANSFORMATION';
export const HANDLEEDITCHANGEVIEW = 'HANDLEEDITCHANGEVIEW';
